---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/dreammoo/keeplocal.swahira.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp sw.js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
